#********************************************************************************
# Copyright (c) 2025 Next Industries s.r.l.
#
# This program and the accompanying materials are made available under the
# terms of the Apache 2.0 which is available at http://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
#
# Project Name:
# Tactigon Soul - Shape
# 
# Release date: 30/09/2025
# Release version: 1.0
#
# Contributors:
# - Massimiliano Bellino
# - Stefano Barbareschi
#********************************************************************************/


networks:
  tactigon-net:
    name: tactigon-net
    driver: bridge

volumes:
  ollama_data:
  tactigon-config:
  open-webui:

services:
  ollama:
    image: ollama/ollama:0.12.10
    container_name: ollama
    restart: unless-stopped
    networks:
      - tactigon-net
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama-init:
    image: ollama/ollama:0.12.10
    container_name: ollama-init
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - tactigon-net
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: >
      sh -c "ollama pull mistral;"
    restart: "no"

  tactigon-shapes:
    image: dev/tactigon-shapes
    container_name: tactigon-shapes
    restart: unless-stopped
    privileged: true
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - tactigon-net
    ports:
      - "5123:5123"
    environment:
      DISPLAY: ${DISPLAY:-:0}
      SDL_AUDIODRIVER: dummy
    volumes:
      - tactigon-config:/app/config
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/dbus:/var/run/dbus

  speech:
    build:
      context: ./speech
      dockerfile: Dockerfile
    container_name: tactigon-speech-socket
    restart: unless-stopped
    networks:
      - tactigon-net
    environment:
      TSS_ADDRESS: tactigon-shapes
      TSS_PORT: 50007
      TSS_CONFIG: config.json

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    networks:
      - tactigon-net
    ports:
      - "3000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - open-webui:/app/backend/data
